# Generated by Django 3.2.9 on 2021-11-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('climate', models.CharField(max_length=255)),
                ('terrain', models.CharField(max_length=255)),
                ('movie_appearances', models.IntegerField()),
            ],
        ),
    ]
